################################################################################
# V1 parent white noise: 128^3, classical slab particle path.
################################################################################

[setup]
GridRes              = 128
BoxLength            = 64
zstart               = 99.0
LPTorder             = 1
DoBaryons            = no
DoBaryonVrel         = no
DoFixing             = no
DoInversion          = no
DoRemoveCornerModes  = no
ParticleLoad         = sc
UseKSectionParticles = no
DumpWhiteNoise       = yes
WhiteNoiseFile       = wn.h5
WhiteNoiseDataset    = WhiteNoise

[cosmology]
ParameterSet  = Planck2018EE+BAO+SN
ZeroRadiation = true
transfer      = eisenstein

[random]
generator = NGENIC
seed      = 12345

[execution]
NumThreads = 2

[output]
format     = gadget_hdf5
filename   = parent.hdf5
UseLongids = true

